# Generated by Django 5.1.4 on 2025-02-16 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_projectmanager_remove_project_projectmanger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ProjectManager',
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.projectmanager'),
        ),
    ]
