# Generated by Django 5.1.4 on 2025-02-19 10:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_project_projectmanager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_manager',
        ),
        migrations.AddField(
            model_name='project',
            name='projectManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.projectmanager'),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
